### ISSUE TITLE
Fix or revert unshiftable addresses

### ISSUE THREAD

**Issue by ribbanya** [doldecomp/melee#465]
- [x] #471
- [x] #473

**Comment by PsiLupan** [comment]
OS and start addresses have to be those pointers because they're the GC memory mapping stuff. No reason to fix those.

The first one could have just used the float and it should have resolved as being in the same compilation unit.

Another instance is FObj - which was our only shift break originally.

Edit: Missed that FObj was linked.

**Comment by PsiLupan** [comment]
Actually misread that. It was the float conversion. I don't remember what my trick was on those. Maybe someone else can weigh in.

**Comment by ribbanya** [comment]
What would be involved in setting up a third automated check against a shifted DOL?

**Comment by ribbanya** [comment]
Discovered this trick while porting `GXLight`:
https://github.com/doldecomp/melee/blob/eece4bec66a91b9dbd7267bef3bb23f0966fd59d/src/dolphin/gx/GXLight.c#L5
https://github.com/doldecomp/melee/blob/eece4bec66a91b9dbd7267bef3bb23f0966fd59d/src/dolphin/gx/GXLight.c#L34-L143
https://github.com/doldecomp/melee/blob/eece4bec66a91b9dbd7267bef3bb23f0966fd59d/asm/dolphin/gx/GXLight/GXLight_001.s#L3-L22

... which results in an `OK`.

Replacing all of the currently unshiftable addresses with relative offsets to another label should resolve this issue.

**Comment by ribbanya** [comment]
Are these actual hardware mappings like `WGPIPE`, or just where the `dolphin/os` module happens to get loaded?
https://github.com/doldecomp/melee/blob/8f11e59dd109bf8184caed22b68d7ba26d593816/src/dolphin/os/OSLink.c#L1-L3

**Comment by kiwi515** [comment]
Not sure if these are "hardware mappings" but they are at least global values, so they cannot be relocated. https://wiibrew.org/wiki/Memory_map
FWIW these are outside of the application's arena (because the globals themselves specify the bounds of the arena)

Most accesses to these are done through [OSPhysicalToCached](https://github.com/kiwi515/open_rvl/blob/main/include/OS/OSAddress.h#L10).

**Comment by ribbanya** [comment]
Makes sense, thank you.
