### ISSUE TITLE
Questions about project status

### ISSUE THREAD

**Issue by ribbanya** [doldecomp/melee#62]
Hi, this is a really great start. I have a couple questions, though.

1. Is this still being worked on?
2. Would you accept contributions which just add comments/pseudocode to assembly, or which rename symbols. to make the code more readable?
3. Is there any consideration for porting parts of the code to C, like [UnclePunch has been doing](https://twitter.com/UnclePunch_/status/1334164728998977536) for his own modifications?

**Comment by PsiLupan** [comment]
1. We don't have the non-Gamecube compiler that was used by Melee. So work halted as a lot of non-matching code appeared to be caused by that.

2. (and 3.) The point of the project is for everything to eventually be C, if the code provided is matching. If it's not readable/using placeholder names, variables should eventually be updated to reflect their actual use.

I had originally worked on [PsiLupan/FRAY](https://github.com/PsiLupan/FRAY) , which I believe was part of UP's starting point. It did not explicitly have matching requirements, which means replacement code was/is wrong in some cases.

**Comment by ribbanya** [comment]
> We don't have the non-Gamecube compiler that was used by Melee. So work halted as a lot of non-matching code appeared to be caused by that.

So are you saying we'd need a custom compiler to unblock the project?

**Comment by PsiLupan** [comment]
> > We don't have the non-Gamecube compiler that was used by Melee. So work halted as a lot of non-matching code appeared to be caused by that.
> 
> So are you saying we'd need a custom compiler to unblock the project?

No, it's still CodeWarrior, just PowerPC generic and not GameCube specific. Which explains why Melee lacks certain optimizations.

Revo has just been unable to locate a copy of it. Though the search lead to finding the earliest GC compiler to date - it was not it.

**Comment by ribbanya** [comment]
Thanks for answering my questions.
